# Website Basic Information
baseURL = "https://bloguk.athenalarm.com/"    # Placeholder URL, change to Cloudflare Pages URL after deployment
title = "Блог Athenalarm"
languageCode = "uk"
theme = "ananke"

# Author Information (optional)
[author]
  name = "Athenalarm"
  email = "info@athenalarm.com"

# Website Menu (optional)
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Головна"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Публікації"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Контакти"
    url = "/contact/"
    weight = 3

# ---------------------------
# Home Page Settings
# ---------------------------
paginate = 5          # Головна сторінка показує останні 5 статей
mainSections = ["posts"]  # На головній сторінці показуються лише статті з type "posts"